name: IceRace
main: com.theseasonedgamers.icerace.IceRace
version: 1.0
commands:
   startGame:
      description: Blank description.
      usage: /<command>
      permission: bc.game
   endGame:
      description: Blank description.
      usage: /<command>
      permission: bc.game
   players:
      description: Blank description.
      usage: /<command>
      permission: bc.game           
   joinGame:
      description: Blank description.
      usage: /<command>    
   begin:
      description: Blank description.
      usage: /<command>
      permission: bc.game         
   automate:
      description: Blank description.
      usage: /<command>
      permission: bc.game
   joinLobby:
      description: Blank description.
      usage: /<command>
      
permissions:
   bc.*:
      description: Gives access to all Race Commands.
      children:
         bc.game: true
   bc.game:
      description: Allows user to run game commands
      default: op